-- Ejecuta este script en Supabase para habilitar login, logout con blacklist y administracion de usuarios.

alter table if exists public.users
  add column if not exists role varchar(20);

update public.users
set role = 'PLAYER'
where role is null;

alter table if exists public.users
  alter column role set default 'PLAYER';

alter table if exists public.users
  alter column role set not null;

alter table if exists public.users
  add column if not exists enabled boolean;

update public.users
set enabled = true
where enabled is null;

alter table if exists public.users
  alter column enabled set default true;

alter table if exists public.users
  alter column enabled set not null;

alter table if exists public.users
  add column if not exists last_login_at timestamp;

create table if not exists public.token_blacklist (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique,
  expires_at timestamp not null,
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_token_blacklist_expires_at
  on public.token_blacklist (expires_at);
