create table if not exists public.unity_access_codes (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  lookup_hash varchar(64) not null unique,
  encrypted_code text not null,
  encryption_iv varchar(32) not null,
  encryption_key_version integer not null,
  created_at timestamp not null,
  regenerated_at timestamp,
  last_emailed_at timestamp
);

create index if not exists idx_unity_access_codes_lookup_hash
  on public.unity_access_codes (lookup_hash);
